-- Generated by scripts/seed-schema.mjs. Do not edit by hand.
INSERT OR REPLACE INTO schema_versions (version, yaml, field_count, source_form, note)
VALUES (2, 'schema_version: 2
worksheet_title: Cataloguing Work Sheet
source_form: eHive Cataloguing Guidelines - July 2023, Appendix 1, pp.10-11
target_system: eHive (Vernon Systems)
derived_from: worksheet.yaml (schema_version 1)
capture_groups:
- id: number
  title: Which object is this?
  order: 1
  voice_prompt: Read out the record number written on the object''s tag, or from the register.
  restricted: false
- id: identify
  title: What is it?
  order: 2
  voice_prompt: Hold the object and tell me what it is. What would you call it, and what type of thing is it?
  restricted: false
- id: describe
  title: Describe it
  order: 3
  voice_prompt: Describe what you''re looking at — shape, colour, parts, decoration. What is it made of? Is there
    any writing, printing, stamps or labels on it? Read those out exactly.
  restricted: false
- id: measure
  title: How big is it?
  order: 4
  voice_prompt: Measure the object and read out the height, width and length. Say the units. If it''s heavy enough
    to matter, give me the weight too.
  restricted: false
- id: condition
  title: What condition is it in?
  order: 5
  voice_prompt: What condition is it in? Any damage, wear, repairs, missing parts, rust or staining? Is it complete,
    or are there pieces missing?
  restricted: false
- id: origin
  title: Who made it, and when?
  order: 6
  voice_prompt: Do you know who made it, where it was made, and roughly when? An approximate date is fine — say
    ''about 1890'' or ''nineteen twenties'' if that''s all you know.
  restricted: false
- id: story
  title: What''s its story?
  order: 7
  voice_prompt: What do you know about its history — who owned it, how it was used, why it matters? And why does
    it belong in this collection?
  restricted: false
- id: collection_management
  title: Where does it live?
  order: 8
  voice_prompt: Where is the object stored or displayed? Does it need any special handling, light, temperature or
    support? Has it been in any exhibitions?
  restricted: false
- id: acquisition
  title: How did we get it?
  order: 9
  voice_prompt: null
  restricted: true
- id: signoff
  title: Sign off
  order: 10
  voice_prompt: null
  restricted: true
sections:
- id: object_details
  title: Object Details
  page: 1
  order: 1
  source: inferred
  description: Core identification, physical description and manufacture information for the object.
  notes: The paper form prints NO section headings. This grouping was inferred during extraction and is a useful
    convenience, not form content.
- id: additional_information
  title: Additional Information
  page: 2
  order: 2
  source: inferred
  description: Contextual, collection-management and interpretive information about the object.
  notes: The paper form prints NO section headings. This grouping was inferred during extraction and is a useful
    convenience, not form content.
- id: acquisition_donor_information
  title: Acquisition & Donor Information
  page: 2
  order: 3
  source: inferred
  description: Details of how the object was acquired and from whom.
  notes: The paper form prints NO section headings. This grouping was inferred during extraction and is a useful
    convenience, not form content.
- id: sign_off
  title: Sign-off
  page: 2
  order: 4
  source: inferred
  description: Completion and cataloguing sign-off, including workflow checklist.
  notes: The paper form prints NO section headings. This grouping was inferred during extraction and is a useful
    convenience, not form content.
- id: media
  title: Photographs & Recording
  page: 0
  order: 0
  source: app_added
  description: Images and audio captured by the app.
  notes: null
- id: record_provenance
  title: Record Provenance
  page: 0
  order: 99
  source: app_added
  description: Who captured this record, when, and how far through review it is.
  notes: null
fields:
- id: registration_number
  label: ''Registration number:''
  display_label: Registration number
  section: object_details
  page: 1
  order: 1
  source: printed
  type: text
  required: null
  hint: As written on the object''s existing tag, or in the Dorrigo register.
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: number
  capture_order: 1
  voice_prompt: What''s the record number for this object?
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: Existing Dorrigo register numbers are entered by hand. No format is enforced - see registration_number_format
    in open_questions.
- id: object_name
  label: ''Object name:''
  display_label: Object name
  section: object_details
  page: 1
  order: 2
  source: printed
  type: text
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: identify
  capture_order: 1
  voice_prompt: What is this object called? Use the everyday name for it.
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: null
- id: title
  label: ''Title (if applicable):''
  display_label: Title (if applicable)
  section: object_details
  page: 1
  order: 3
  source: printed
  type: text
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: identify
  capture_order: 3
  voice_prompt: Does it have a formal title? Skip this if not.
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: null
- id: object_type
  label: ''Object Type:''
  display_label: Object Type
  section: object_details
  page: 1
  order: 4
  source: printed
  type: text
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: identify
  capture_order: 2
  voice_prompt: What type of object is it?
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: null
- id: description
  label: ''Description:''
  display_label: Description
  section: object_details
  page: 1
  order: 5
  source: printed
  type: longtext
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: describe
  capture_order: 1
  voice_prompt: Describe the object — shape, colour, parts, decoration.
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: Printed as three ruled lines following the label.
- id: materials
  label: ''Materials:''
  display_label: Materials
  section: object_details
  page: 1
  order: 6
  source: printed
  type: text
  required: null
  hint: null
  options: null
  units: null
  repeatable: true
  sensitivity: public
  capture_group: describe
  capture_order: 2
  voice_prompt: What is it made of? List each material.
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: null
- id: marks_and_inscriptions
  label: ''Marks and inscriptions:''
  display_label: Marks and inscriptions
  section: object_details
  page: 1
  order: 7
  source: printed
  type: longtext
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: describe
  capture_order: 3
  voice_prompt: Read out any writing, stamps, labels or maker''s marks, exactly as they appear.
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: Printed as three ruled lines following the label.
- id: dimensions
  label: ''Dimensions (h x w x l):''
  display_label: Dimensions (h x w x l)
  section: object_details
  page: 1
  order: 8
  source: printed
  type: measurement
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: measure
  capture_order: 1
  voice_prompt: Give the height, width and length, and say the units.
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields:
  - id: dimensions_height
    label: h
    display_label: h
    section: object_details
    page: 1
    order: 1
    source: printed
    type: number
    required: null
    hint: null
    options: null
    units: null
    repeatable: false
    sensitivity: public
    mapping:
      ehive: UNVERIFIED
      note: confirm against eHive import spreadsheet
    subfields: null
    example: null
    notes: null
  - id: dimensions_width
    label: w
    display_label: w
    section: object_details
    page: 1
    order: 2
    source: printed
    type: number
    required: null
    hint: null
    options: null
    units: null
    repeatable: false
    sensitivity: public
    mapping:
      ehive: UNVERIFIED
      note: confirm against eHive import spreadsheet
    subfields: null
    example: null
    notes: null
  - id: dimensions_length
    label: l
    display_label: l
    section: object_details
    page: 1
    order: 3
    source: printed
    type: number
    required: null
    hint: null
    options: null
    units: null
    repeatable: false
    sensitivity: public
    mapping:
      ehive: UNVERIFIED
      note: confirm against eHive import spreadsheet
    subfields: null
    example: null
    notes: null
  - id: dimensions_units
    label: units
    display_label: Units
    section: object_details
    page: 1
    order: 4
    source: app_added
    type: enum
    required: true
    hint: Not printed on the form. Museum must choose a house standard.
    options:
    - value: mm
      label: mm
    - value: cm
      label: cm
    - value: m
      label: m
    units: null
    repeatable: false
    sensitivity: public
    mapping: null
    subfields: null
    example: null
    notes: ''Added by the app. DECISION NEEDED: confirm the museum''''s preferred unit and set it as default.''
  example: null
  notes: Form prints no unit. App adds a required unit selector — see dimensions_units.
- id: weight
  label: ''Weight (if necessary):''
  display_label: Weight (if necessary)
  section: object_details
  page: 1
  order: 9
  source: printed
  type: measurement
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: measure
  capture_order: 2
  voice_prompt: How heavy is it? Only if the weight matters.
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields:
  - id: weight_value
    label: weight
    display_label: Weight
    section: object_details
    page: 1
    order: 1
    source: printed
    type: number
    required: null
    hint: null
    options: null
    units: null
    repeatable: false
    sensitivity: public
    mapping: null
    subfields: null
    example: null
    notes: null
  - id: weight_units
    label: units
    display_label: Units
    section: object_details
    page: 1
    order: 2
    source: app_added
    type: enum
    required: null
    hint: null
    options:
    - value: g
      label: g
    - value: kg
      label: kg
    units: null
    repeatable: false
    sensitivity: public
    mapping: null
    subfields: null
    example: null
    notes: null
  example: null
  notes: Single free-text value; no unit printed on form.
- id: condition_and_completeness
  label: ''Condition and completeness:''
  display_label: Condition and completeness
  section: object_details
  page: 1
  order: 10
  source: printed
  type: longtext
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: condition
  capture_order: 1
  voice_prompt: What condition is it in, and is anything missing or damaged?
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: Printed as three ruled lines following the label.
- id: maker
  label: ''Maker:''
  display_label: Maker
  section: object_details
  page: 1
  order: 11
  source: printed
  type: text
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: origin
  capture_order: 1
  voice_prompt: Who made it, if known?
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: null
- id: secondary_maker
  label: ''Secondary maker:''
  display_label: Secondary maker
  section: object_details
  page: 1
  order: 12
  source: printed
  type: text
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: origin
  capture_order: 2
  voice_prompt: Was anyone else involved in making it?
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: null
- id: place_manufactured
  label: ''Place manufactured:''
  display_label: Place manufactured
  section: object_details
  page: 1
  order: 13
  source: printed
  type: text
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: origin
  capture_order: 3
  voice_prompt: Where was it made?
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: null
- id: date_manufactured
  label: ''Date manufactured:''
  display_label: Date manufactured
  section: object_details
  page: 1
  order: 14
  source: printed
  type: fuzzy_date
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: origin
  capture_order: 4
  voice_prompt: When was it made? An approximate date is fine.
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: null
- id: provenance
  label: ''Provenance (history, previous owners, historical importance):''
  display_label: Provenance (history, previous owners, historical importance)
  section: object_details
  page: 1
  order: 15
  source: printed
  type: longtext
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: story
  capture_order: 1
  voice_prompt: What''s its history — previous owners, how it was used, why it''s significant?
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: Printed as three ruled lines following the label.
- id: references
  label: ''References (books and files):''
  display_label: References (books and files)
  section: additional_information
  page: 2
  order: 16
  source: printed
  type: text
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: collection_management
  capture_order: 5
  voice_prompt: Are there any books, files or documents that mention it?
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: null
- id: location
  label: ''Location:''
  display_label: Location
  section: additional_information
  page: 2
  order: 17
  source: printed
  type: longtext
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: collection_management
  capture_order: 1
  voice_prompt: Where is the object stored or displayed?
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: Printed as two ruled lines following the label.
- id: location_date
  label: ''Location date:''
  display_label: Location date
  section: additional_information
  page: 2
  order: 18
  source: printed
  type: date
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: collection_management
  capture_order: 2
  voice_prompt: What''s today''s date, or the date it was moved there?
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: null
- id: relevance_to_the_collection
  label: ''Relevance to the Collection:''
  display_label: Relevance to the Collection
  section: additional_information
  page: 2
  order: 19
  source: printed
  type: longtext
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: story
  capture_order: 2
  voice_prompt: Why does this object belong in our collection?
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: Printed as two ruled lines following the label.
- id: storage_and_display_requirements
  label: ''Storage and display requirements:''
  display_label: Storage and display requirements
  section: additional_information
  page: 2
  order: 20
  source: printed
  type: longtext
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: collection_management
  capture_order: 3
  voice_prompt: Does it need any special handling, support or conditions?
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: Printed as three ruled lines following the label.
- id: exhibition_history
  label: ''Exhibition history:''
  display_label: Exhibition history
  section: additional_information
  page: 2
  order: 21
  source: printed
  type: longtext
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: collection_management
  capture_order: 4
  voice_prompt: Has it been displayed in any exhibitions?
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: Printed as two ruled lines following the label.
- id: subjects_key_words_tags
  label: ''Subjects, Key Words, Tags:''
  display_label: Subjects, Key Words, Tags
  section: additional_information
  page: 2
  order: 22
  source: printed
  type: longtext
  required: null
  hint: null
  options: null
  units: null
  repeatable: true
  sensitivity: public
  capture_group: collection_management
  capture_order: 6
  voice_prompt: What subjects or keywords would help someone find this object?
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: Printed as two ruled lines following the label.
- id: date_of_acquisition
  label: ''Date of acquisition:''
  display_label: Date of acquisition
  section: acquisition_donor_information
  page: 2
  order: 23
  source: printed
  type: date
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: acquisition
  capture_order: 1
  voice_prompt: null
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: null
- id: how_was_it_acquired
  label: How was it acquired?
  display_label: How was it acquired?
  section: acquisition_donor_information
  page: 2
  order: 24
  source: printed
  type: enum
  required: null
  hint: null
  options:
  - value: donation
    label: Donation
  - value: purchase
    label: Purchase
  - value: transfer
    label: Transfer
  - value: unknown
    label: Unknown
  units: null
  repeatable: false
  sensitivity: public
  capture_group: acquisition
  capture_order: 2
  voice_prompt: null
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: ''Form prints a ruled line after ''''Unknown'''' with no label. QUESTION FOR THE MUSEUM: is that line for elaborating
    on an unknown source, or a de facto ''''Other'''' option? App currently treats it as an optional free-text note
    alongside the choice.''
- id: tax_incentive_gift_number
  label: ''Tax incentive gift number (if applicable):''
  display_label: Tax incentive gift number (if applicable)
  section: acquisition_donor_information
  page: 2
  order: 25
  source: printed
  type: text
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: restricted
  capture_group: acquisition
  capture_order: 3
  voice_prompt: null
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: null
- id: donor_source_name
  label: ''Donor/Source name:''
  display_label: Donor/Source name
  section: acquisition_donor_information
  page: 2
  order: 26
  source: printed
  type: text
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: restricted
  capture_group: acquisition
  capture_order: 4
  voice_prompt: null
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: null
- id: address
  label: ''Address:''
  display_label: Address
  section: acquisition_donor_information
  page: 2
  order: 27
  source: printed
  type: text
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: restricted
  capture_group: acquisition
  capture_order: 5
  voice_prompt: null
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: null
- id: email
  label: ''Email:''
  display_label: Email
  section: acquisition_donor_information
  page: 2
  order: 28
  source: printed
  type: text
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: restricted
  capture_group: acquisition
  capture_order: 6
  voice_prompt: null
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: null
- id: phone_numbers
  label: ''Phone number/s:''
  display_label: Phone number/s
  section: acquisition_donor_information
  page: 2
  order: 29
  source: printed
  type: text
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: restricted
  capture_group: acquisition
  capture_order: 7
  voice_prompt: null
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: null
- id: completed_by
  label: ''Completed by:''
  display_label: Completed by
  section: sign_off
  page: 2
  order: 30
  source: printed
  type: signature
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: signoff
  capture_order: 2
  voice_prompt: null
  autofill: current_user_and_date
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields:
  - id: completed_by_name
    label: Completed by
    display_label: Completed by
    section: sign_off
    page: 2
    order: 1
    source: printed
    type: text
    required: null
    hint: null
    options: null
    units: null
    repeatable: false
    sensitivity: public
    mapping:
      ehive: UNVERIFIED
      note: confirm against eHive import spreadsheet
    subfields: null
    example: null
    notes: null
  - id: completed_by_date
    label: Date
    display_label: Date
    section: sign_off
    page: 2
    order: 2
    source: printed
    type: date
    required: null
    hint: null
    options: null
    units: null
    repeatable: false
    sensitivity: public
    mapping:
      ehive: UNVERIFIED
      note: confirm against eHive import spreadsheet
    subfields: null
    example: null
    notes: null
  example: null
  notes: An additional blank ruled line follows this row on the form, possibly for a signature; no separate label
    printed.
- id: catalogued_by
  label: ''Catalogued by:''
  display_label: Catalogued by
  section: sign_off
  page: 2
  order: 31
  source: printed
  type: signature
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: signoff
  capture_order: 3
  voice_prompt: null
  autofill: current_user_and_date
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields:
  - id: catalogued_by_name
    label: Catalogued by
    display_label: Catalogued by
    section: sign_off
    page: 2
    order: 1
    source: printed
    type: text
    required: null
    hint: null
    options: null
    units: null
    repeatable: false
    sensitivity: public
    mapping:
      ehive: UNVERIFIED
      note: confirm against eHive import spreadsheet
    subfields: null
    example: null
    notes: null
  - id: catalogued_by_date
    label: Date
    display_label: Date
    section: sign_off
    page: 2
    order: 2
    source: printed
    type: date
    required: null
    hint: null
    options: null
    units: null
    repeatable: false
    sensitivity: public
    mapping:
      ehive: UNVERIFIED
      note: confirm against eHive import spreadsheet
    subfields: null
    example: null
    notes: null
  example: null
  notes: null
- id: numbered
  label: Numbered
  display_label: Numbered
  section: sign_off
  page: 2
  order: 32
  source: printed
  type: boolean
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: signoff
  capture_order: 4
  voice_prompt: null
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: One of four workflow checkboxes printed in a row.
- id: acknowledgement_sent
  label: Acknowledgement Sent
  display_label: Acknowledgement Sent
  section: sign_off
  page: 2
  order: 33
  source: printed
  type: boolean
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: signoff
  capture_order: 5
  voice_prompt: null
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: One of four workflow checkboxes printed in a row.
- id: digitised
  label: Digitised
  display_label: Digitised
  section: sign_off
  page: 2
  order: 34
  source: printed
  type: boolean
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: signoff
  capture_order: 6
  voice_prompt: null
  autofill: set_true_on_photo_upload
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: One of four workflow checkboxes printed in a row.
- id: entered_to_ehive
  label: Entered to ehive
  display_label: Entered to ehive
  section: sign_off
  page: 2
  order: 35
  source: printed
  type: boolean
  required: null
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: signoff
  capture_order: 7
  voice_prompt: null
  autofill: set_true_on_successful_export
  mapping:
    ehive: UNVERIFIED
    note: confirm against eHive import spreadsheet
  subfields: null
  example: null
  notes: One of four workflow checkboxes printed in a row.
- id: object_photographs
  label: Photographs
  display_label: Photographs
  section: media
  page: 0
  order: 101
  source: app_added
  type: image
  required: true
  hint: null
  options: null
  units: null
  repeatable: true
  sensitivity: public
  capture_group: identify
  capture_order: 0
  voice_prompt: Take photographs of the object — an overall view, then any marks, labels or damage.
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: eHive supports images on object records
  subfields: null
  example: null
  notes: Not on the paper form. This is the whole point of the app; eHive records carry images.
- id: primary_image
  label: Primary image
  display_label: Primary image
  section: media
  page: 0
  order: 102
  source: app_added
  type: text
  required: false
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: null
  capture_order: null
  voice_prompt: null
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: eHive supports images on object records
  subfields: null
  example: null
  notes: Id of the photograph used as the record''s lead image.
- id: voice_recording
  label: Voice recording
  display_label: Voice recording
  section: media
  page: 0
  order: 103
  source: app_added
  type: audio
  required: false
  hint: null
  options: null
  units: null
  repeatable: true
  sensitivity: public
  capture_group: null
  capture_order: null
  voice_prompt: null
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: eHive supports images on object records
  subfields: null
  example: null
  notes: Raw audio kept as evidence. If the transcription mis-hears something, the source survives.
- id: transcript
  label: Transcript
  display_label: Transcript
  section: media
  page: 0
  order: 104
  source: app_added
  type: longtext
  required: false
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: public
  capture_group: null
  capture_order: null
  voice_prompt: null
  autofill: null
  mapping:
    ehive: UNVERIFIED
    note: eHive supports images on object records
  subfields: null
  example: null
  notes: Verbatim transcript before it is split across fields.
- id: record_status
  label: Record status
  display_label: Record status
  section: record_provenance
  page: 0
  order: 205
  source: app_added
  type: enum
  required: false
  hint: null
  options:
  - value: draft
    label: Draft
  - value: review
    label: Awaiting review
  - value: confirmed
    label: Confirmed
  - value: exported
    label: Exported to eHive
  units: null
  repeatable: false
  sensitivity: internal
  capture_group: null
  capture_order: null
  voice_prompt: null
  autofill: app_managed
  mapping: null
  subfields: null
  example: null
  notes: Paper had no draft state. A volunteer''s first pass should not be authoritative.
- id: captured_by
  label: Captured by
  display_label: Captured by
  section: record_provenance
  page: 0
  order: 206
  source: app_added
  type: text
  required: false
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: internal
  capture_group: null
  capture_order: null
  voice_prompt: null
  autofill: app_managed
  mapping: null
  subfields: null
  example: null
  notes: Volunteer who made the recording.
- id: captured_at
  label: Captured at
  display_label: Captured at
  section: record_provenance
  page: 0
  order: 207
  source: app_added
  type: date
  required: false
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: internal
  capture_group: null
  capture_order: null
  voice_prompt: null
  autofill: app_managed
  mapping: null
  subfields: null
  example: null
  notes: Timestamp set by the app.
- id: reviewed_by
  label: Reviewed by
  display_label: Reviewed by
  section: record_provenance
  page: 0
  order: 208
  source: app_added
  type: text
  required: false
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: internal
  capture_group: null
  capture_order: null
  voice_prompt: null
  autofill: app_managed
  mapping: null
  subfields: null
  example: null
  notes: Second pair of eyes before Confirmed.
- id: field_confidence
  label: Field confidence
  display_label: Field confidence
  section: record_provenance
  page: 0
  order: 209
  source: app_added
  type: table
  required: false
  hint: null
  options: null
  units: null
  repeatable: false
  sensitivity: internal
  capture_group: null
  capture_order: null
  voice_prompt: null
  autofill: app_managed
  mapping: null
  subfields: null
  example: null
  notes: ''Per-field flag: spoken, inferred by the model, or typed by hand. Drives what review highlights.''
open_questions:
- ''Registration number format: is there a pattern for Dorrigo numbers that the app should check against (e.g. YYYY.NNN)?
  Currently accepted as free text with no validation.''
- ''Dimensions: which unit is the museum''''s house standard - mm or cm?''
- ''The ruled line after the ''''Unknown'''' acquisition tickbox: elaboration, or an ''''Other'''' option?''
- Who assigns the registration number - the app, or a committee member beforehand?
- Should cataloguing volunteers see the donor block at all, or does a committee member enter it separately?
- Confirm every mapping.ehive value against the actual eHive import spreadsheet before any export is built.
', 44, 'eHive Cataloguing Guidelines - July 2023, Appendix 1, pp.10-11', 'Loaded 2026-08-11 from schema/worksheet.v2.yaml');
