/**
 * Generates the SQL that loads schema/worksheet.v2.yaml into the schema_versions
 * table, then you apply it with wrangler.
 *
 *   node scripts/seed-schema.mjs
 *   npx wrangler d1 execute artefact-catalogue --remote --file=migrations/seed-schema.sql
 *
 * Why a script rather than a one-line command: the YAML contains apostrophes
 * ("object's tag", "What's its story?"), and a single unescaped one ends the SQL
 * string early and turns the rest of the file into invalid syntax. SQL escapes a
 * quote by doubling it. Getting that wrong doesn't fail loudly — it can load a
 * truncated schema, which is worse than loading none.
 *
 * Rerunnable: INSERT OR REPLACE, so bumping the schema and running this again
 * updates the row rather than erroring.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import yamlParser from "js-yaml";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

const SCHEMA_PATH = resolve(root, "schema/worksheet.v2.yaml");
const OUT_PATH = resolve(root, "migrations/seed-schema.sql");
const D1_STATEMENT_LIMIT = 100_000;

const yaml = readFileSync(SCHEMA_PATH, "utf8");

// Parse rather than pattern-match. A regex for "^- id:" also catches the
// capture_groups and sections lists, which silently inflates the field count —
// and a wrong count stored next to the schema is exactly the kind of small lie
// that misleads someone reading an export years from now.
const parsed = yamlParser.load(yaml);
const version = parsed?.schema_version;
const sourceForm = parsed?.source_form ?? "";
const fieldCount = Array.isArray(parsed?.fields) ? parsed.fields.length : 0;

if (!Number.isInteger(version)) {
  console.error("Could not read schema_version from the YAML. Aborting rather than guessing.");
  process.exit(1);
}
if (fieldCount === 0) {
  console.error("The YAML has no fields list. Aborting.");
  process.exit(1);
}

const q = (text) => `'${String(text).replace(/'/g, "''")}'`;

const sql =
  `-- Generated by scripts/seed-schema.mjs. Do not edit by hand.\n` +
  `INSERT OR REPLACE INTO schema_versions (version, yaml, field_count, source_form, note)\n` +
  `VALUES (${version}, ${q(yaml)}, ${fieldCount}, ${q(sourceForm)}, ${q(
    `Loaded ${new Date().toISOString().slice(0, 10)} from schema/worksheet.v2.yaml`
  )});\n`;

if (sql.length > D1_STATEMENT_LIMIT) {
  console.error(
    `Generated statement is ${sql.length} bytes, over D1's ${D1_STATEMENT_LIMIT} byte limit.\n` +
      `The schema file has grown too large to store in one statement — split it or compress it.`
  );
  process.exit(1);
}

mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, sql, "utf8");

console.log(`Wrote ${OUT_PATH}`);
console.log(`  schema version : ${version}`);
console.log(`  fields         : ${fieldCount}`);
console.log(`  source form    : ${sourceForm}`);
console.log(`  statement size : ${sql.length} bytes (limit ${D1_STATEMENT_LIMIT})`);
console.log(`\nNow run:\n  npx wrangler d1 execute artefact-catalogue --remote --file=migrations/seed-schema.sql`);
